pipeline:
  redis:
    image: redis
    detach: true
  database:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    detach: true
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    environment:
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=database
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    detach: true
  test:
    image: php:7.2.0-cli
    commands: php run.php

matrix:
  OWNCLOUD_VERSION:
    - 9.0.7
    - 9.1.7
    - 10.0.3
